apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: strigus
  name: strigus
  namespace: default
spec:
  replicas: 15
  selector:
    matchLabels:
      app: strigus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strigus
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
